const mongoose = require('mongoose');

const settlementSchema = new mongoose.Schema({
  seller: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Seller',
    required: true
  },
  orders: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Order'
  }],
  amount: {
    type: Number,
    required: true
  },
  fees: {
    type: Number,
    default: 0
  },
  tax: {
    type: Number,
    default: 0
  },
  penalties: {
    type: Number,
    default: 0
  },
  netAmount: {
    type: Number,
    required: function() {
      return this.amount - (this.fees + this.tax + this.penalties);
    }
  },
  currency: {
    type: String,
    default: 'INR'
  },
  status: {
    type: String,
    enum: ['pending', 'processing', 'completed', 'failed', 'cancelled'],
    default: 'pending'
  },
  statusHistory: [{
    status: {
      type: String,
      enum: ['pending', 'processing', 'completed', 'failed', 'cancelled']
    },
    timestamp: {
      type: Date,
      default: Date.now
    },
    comment: String,
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Admin'
    }
  }],
  paymentMethod: {
    type: String,
    enum: ['bank_transfer', 'upi', 'wallet'],
    default: 'bank_transfer'
  },
  bankDetails: {
    accountHolderName: String,
    accountNumber: String,
    bankName: String,
    ifscCode: String,
    accountType: {
      type: String,
      enum: ['savings', 'current']
    }
  },
  upiDetails: {
    upiId: String,
    name: String
  },
  transactionId: String,
  transactionDate: Date,
  reference: String,
  notes: String,
  invoice: {
    number: String,
    url: String,
    generatedAt: Date
  },
  processedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Admin'
  },
  settlementPeriod: {
    startDate: Date,
    endDate: Date
  },
  isAutoGenerated: {
    type: Boolean,
    default: true
  }
}, {
  timestamps: true
});

// Create indexes for faster queries
settlementSchema.index({ seller: 1 });
settlementSchema.index({ status: 1 });
settlementSchema.index({ createdAt: -1 });

const Settlement = mongoose.model('Settlement', settlementSchema);

module.exports = Settlement;